In [120]:
import pandas as pd

In [121]:
df=pd.read_csv('C:/Users/SHIVANSHU SRIVASTAVA/OneDrive/Desktop/ml by upflair/PANDAS/laptopPrice.csv')
df.head(2)

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5

In [122]:
df.tail()

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990,3 stars,0,0
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990,3 stars,0,0
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990,3 stars,0,0
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990,3 stars,0,0
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490,4 stars,18,4

In [123]:
df.info()# it tell us the information of data set

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 823 entries, 0 to 822
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   brand              823 non-null    object
 1   processor_brand    823 non-null    object
 2   processor_name     823 non-null    object
 3   processor_gnrtn    823 non-null    object
 4   ram_gb             823 non-null    object
 5   ram_type           823 non-null    object
 6   ssd                823 non-null    object
 7   hdd                823 non-null    object
 8   os                 823 non-null    object
 9   os_bit             823 non-null    object
 10  graphic_card_gb    823 non-null    object
 11  weight             823 non-null    object
 12  warranty           823 non-null    object
 13  Touchscreen        823 non-null    object
 14  msoffice           823 non-null    object
 15  Price              823 non-null    int64
 16  rating             823 non-null    object
 17  Number of Ratings  823 non-null    int64
 18  Number of Reviews  823 non-null    int64
dtypes: int64(3), object(16)
memory usage: 122.3+ KB

In [124]:
df.describe() # to get a summary of the data or statical data  of data

               Price  Number of Ratings  Number of Reviews
count     823.000000         823.000000         823.000000
mean    76745.177400         315.301337          37.609964
std     45101.790525        1047.382654         121.728017
min     16990.000000           0.000000           0.000000
25%     46095.000000           0.000000           0.000000
50%     64990.000000          17.000000           2.000000
75%     89636.000000         139.500000          18.000000
max    441990.000000       15279.000000        1947.000000

In [125]:
df.dtypes # it tellsus the data type of each column

brand                object
processor_brand      object
processor_name       object
processor_gnrtn      object
ram_gb               object
ram_type             object
ssd                  object
hdd                  object
os                   object
os_bit               object
graphic_card_gb      object
weight               object
warranty             object
Touchscreen          object
msoffice             object
Price                 int64
rating               object
Number of Ratings     int64
Number of Reviews     int64
dtype: object

In [126]:
df.columns # it show all the columns of the dataframe

Index(['brand', 'processor_brand', 'processor_name', 'processor_gnrtn',
       'ram_gb', 'ram_type', 'ssd', 'hdd', 'os', 'os_bit', 'graphic_card_gb',
       'weight', 'warranty', 'Touchscreen', 'msoffice', 'Price', 'rating',
       'Number of Ratings', 'Number of Reviews'],
      dtype='object')

In [127]:
num_column=df.select_dtypes(exclude='object') # print  all numeric values of data set  it exclude object type

In [128]:
num_column

      Price  Number of Ratings  Number of Reviews
0     34649                  3                  0
1     38999                 65                  5
2     39999                  8                  1
3     69990                  0                  0
4     26990                  0                  0
..      ...                ...                ...
818  135990                  0                  0
819  144990                  0                  0
820  149990                  0                  0
821  142990                  0                  0
822   57490                 18                  4

[823 rows x 3 columns]

In [129]:
cat_columns=df.select_dtypes(include='O')# it include all dataa type of object

In [130]:
cat_columns

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,rating
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,2 stars
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,3 stars
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,3 stars
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,3 stars
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,3 stars
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,3 stars
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,3 stars
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,3 stars
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,3 stars
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,4 stars

In [131]:
cat_columns.head()

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,rating
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,2 stars
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,3 stars
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,3 stars
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,3 stars
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,3 stars

In [132]:
num_column.head()

   Price  Number of Ratings  Number of Reviews
0  34649                  3                  0
1  38999                 65                  5
2  39999                  8                  1
3  69990                  0                  0
4  26990                  0                  0

In [133]:
# add both numeric and object dat type 
pd.concat([num_column,cat_columns])

,Price,Number of Ratings,Number of Reviews,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,rating
0,34649.0,3.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,38999.0,65.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,39999.0,8.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,69990.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,26990.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,NaN,NaN,NaN,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,3 stars
819,NaN,NaN,NaN,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,3 stars
820,NaN,NaN,NaN,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,3 stars
821,NaN,NaN,NaN,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,3 stars
822,NaN,NaN,NaN,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,4 stars

In [134]:
cat_columns['brand'].unique() # it tel us the unique values in the column brand

array(['ASUS', 'Lenovo', 'acer', 'Avita', 'HP', 'DELL', 'MSI', 'APPLE'],
      dtype=object)

In [135]:
cat_columns['brand'].nunique()

8

In [136]:
cat_columns['brand']

0        ASUS
1      Lenovo
2      Lenovo
3        ASUS
4        ASUS
        ...
818      ASUS
819      ASUS
820      ASUS
821      ASUS
822    Lenovo
Name: brand, Length: 823, dtype: object

In [137]:
cat_columns['processor_brand'].nunique()

3

In [138]:
cat_columns['processor_name'].nunique()

11

In [139]:
cat_columns['processor_name'].unique()

array(['Core i3', 'Core i5', 'Celeron Dual', 'Ryzen 5', 'Core i7',
       'Core i9', 'M1', 'Pentium Quad', 'Ryzen 3', 'Ryzen 7', 'Ryzen 9'],
      dtype=object)

In [140]:
cat_columns['processor_gnrtn'].nunique()

8

In [141]:
cat_columns['os'].nunique()

3

In [142]:
cat_columns['ram_type'].nunique()

6

In [143]:
cat_columns['ssd'].nunique()

7

In [144]:
cat_columns['warranty'].nunique()

4

In [145]:
df['brand'].value_counts() # it tell the number of each brand

brand
ASUS      249
DELL      151
Lenovo    144
HP        136
acer       51
MSI        50
APPLE      28
Avita      14
Name: count, dtype: int64

In [146]:
df.brand.unique()

array(['ASUS', 'Lenovo', 'acer', 'Avita', 'HP', 'DELL', 'MSI', 'APPLE'],
      dtype=object)

In [147]:
apple=df[df['brand']=="APPLE"] # if we want to get only the rows where brand is APPLE

In [148]:
apple

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
309,APPLE,Intel,Core i5,10th,8 GB,LPDDR4X,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,159990,4 stars,32,5
310,APPLE,Intel,Core i5,8th,8 GB,DDR3,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,172090,4 stars,108,13
407,APPLE,Intel,Core i5,10th,16 GB,LPDDR4X,1024 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,179990,4 stars,31,3
408,APPLE,Intel,Core i5,10th,16 GB,LPDDR4X,1024 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,179990,4 stars,91,5
599,APPLE,M1,M1,10th,8 GB,DDR4,256 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,85990,4 stars,6725,629
600,APPLE,M1,M1,10th,8 GB,DDR4,256 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,112990,4 stars,640,70
601,APPLE,M1,M1,10th,16 GB,DDR4,256 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,104990,4 stars,45,4
602,APPLE,M1,M1,10th,8 GB,DDR4,256 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,112990,4 stars,640,70
603,APPLE,M1,M1,10th,16 GB,DDR4,256 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,132990,4 stars,640,70
604,APPLE,M1,M1,10th,16 GB,DDR4,256 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,104990,4 stars,45,4
605,APPLE,M1,M1,10th,8 GB,DDR4,256 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,85990,4 stars,6725,629
606,APPLE,M1,M1,10th,16 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,149990,4 stars,640,70
607,APPLE,M1,M1,10th,8 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,125990,4 stars,399,45
608,APPLE,M1,M1,10th,8 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,103990,4 stars,809,91
609,APPLE,M1,M1,10th,8 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,101990,4 stars,809,91
610,APPLE,M1,M1,10th,8 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,104990,4 stars,6725,629
611,APPLE,M1,M1,10th,8 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,131990,4 stars,399,45
612,APPLE,M1,M1,10th,16 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,128990,4 stars,45,4
613,APPLE,M1,M1,10th,16 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,184990,4 stars,42,8
614,APPLE,M1,M1,10th,16 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,225990,4 stars,42,8
615,APPLE,M1,M1,10th,4 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,124990,4 stars,45,4
616,APPLE,M1,M1,10th,8 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,104990,4 stars,6725,629
617,APPLE,M1,M1,10th,8 GB,DDR4,1024 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,149990,4 stars,640,70
618,APPLE,M1,M1,10th,16 GB,DDR4,1024 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,169990,4 stars,640,70
619,APPLE,M1,M1,10th,16 GB,DDR4,1024 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,225990,4 stars,42,8
620,APPLE,M1,M1,10th,16 GB,DDR4,1024 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,243990,4 stars,42,8
621,APPLE,M1,M1,10th,32 GB,DDR4,1024 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,309990,5 stars,3,1
622,APPLE,M1,M1,10th,16 GB,DDR4,1024 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,225990,4 stars,42,8

In [149]:
asus=df[df['brand']=="ASUS"] 
asus

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0
5,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,22990,3 stars,0,0
6,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,21990,3 stars,31,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
817,ASUS,AMD,Ryzen 9,Not Available,4 GB,LPDDR4X,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,Yes,Yes,234990,3 stars,0,0
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990,3 stars,0,0
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990,3 stars,0,0
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990,3 stars,0,0
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990,3 stars,0,0

In [150]:
apple['processor_brand'].unique()

array(['Intel', 'M1'], dtype=object)

In [151]:
apple_m1=apple[apple['processor_brand']=='M1']
apple_m1

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
599,APPLE,M1,M1,10th,8 GB,DDR4,256 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,85990,4 stars,6725,629
600,APPLE,M1,M1,10th,8 GB,DDR4,256 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,112990,4 stars,640,70
601,APPLE,M1,M1,10th,16 GB,DDR4,256 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,104990,4 stars,45,4
602,APPLE,M1,M1,10th,8 GB,DDR4,256 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,112990,4 stars,640,70
603,APPLE,M1,M1,10th,16 GB,DDR4,256 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,132990,4 stars,640,70
604,APPLE,M1,M1,10th,16 GB,DDR4,256 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,104990,4 stars,45,4
605,APPLE,M1,M1,10th,8 GB,DDR4,256 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,85990,4 stars,6725,629
606,APPLE,M1,M1,10th,16 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,149990,4 stars,640,70
607,APPLE,M1,M1,10th,8 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,125990,4 stars,399,45
608,APPLE,M1,M1,10th,8 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,103990,4 stars,809,91
609,APPLE,M1,M1,10th,8 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,101990,4 stars,809,91
610,APPLE,M1,M1,10th,8 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,104990,4 stars,6725,629
611,APPLE,M1,M1,10th,8 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,131990,4 stars,399,45
612,APPLE,M1,M1,10th,16 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,128990,4 stars,45,4
613,APPLE,M1,M1,10th,16 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,184990,4 stars,42,8
614,APPLE,M1,M1,10th,16 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,225990,4 stars,42,8
615,APPLE,M1,M1,10th,4 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,124990,4 stars,45,4
616,APPLE,M1,M1,10th,8 GB,DDR4,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,104990,4 stars,6725,629
617,APPLE,M1,M1,10th,8 GB,DDR4,1024 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,149990,4 stars,640,70
618,APPLE,M1,M1,10th,16 GB,DDR4,1024 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,169990,4 stars,640,70
619,APPLE,M1,M1,10th,16 GB,DDR4,1024 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,225990,4 stars,42,8
620,APPLE,M1,M1,10th,16 GB,DDR4,1024 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,243990,4 stars,42,8
621,APPLE,M1,M1,10th,32 GB,DDR4,1024 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,309990,5 stars,3,1
622,APPLE,M1,M1,10th,16 GB,DDR4,1024 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,225990,4 stars,42,8

In [152]:
apple_m1_touch=apple[apple[apple['processor_brand']=='M1']=='Touchscreen']
apple_m1_touch

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
309,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
310,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
407,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
408,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
599,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
601,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
602,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
603,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
604,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
605,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
606,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
607,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
608,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
609,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
610,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
611,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
612,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
613,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
614,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
615,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
616,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
617,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
618,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
619,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
620,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
621,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
622,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [153]:
apple_max_price=apple.loc[apple['Price'].idxmax()]
apple_max_price

brand                  APPLE
processor_brand           M1
processor_name            M1
processor_gnrtn         10th
ram_gb                 32 GB
ram_type                DDR4
ssd                  1024 GB
hdd                     0 GB
os                       Mac
os_bit                64-bit
graphic_card_gb         0 GB
weight                Casual
warranty              1 year
Touchscreen               No
msoffice                  No
Price                 309990
rating               5 stars
Number of Ratings          3
Number of Reviews          1
Name: 621, dtype: object

# apple laptop processor brand intel ram 8 gb and price under 1000000

In [154]:




# # Filter the DataFrame
# apple_task = apple[
#     (apple['brand'] == 'Apple') &
#     (apple['processor_brand'] == 'Intel') AND
#     (apple['RAM'] == 8 GB) &
#     (apple['price'] < 100000)
# ]

# print(apple_task)

In [155]:
# Filter the DataFrame
apple_task = apple[
    (apple['brand'] == 'APPLE') &
    (apple['processor_brand'] == 'Intel') &
    (apple['ram_gb'] == '8 GB') &
    (apple['Price'] < 200000)
]

print(apple_task)

     brand processor_brand processor_name processor_gnrtn ram_gb ram_type  \
309  APPLE           Intel        Core i5            10th   8 GB  LPDDR4X
310  APPLE           Intel        Core i5             8th   8 GB     DDR3

        ssd   hdd   os  os_bit graphic_card_gb  weight warranty Touchscreen  \
309  512 GB  0 GB  Mac  64-bit            0 GB  Casual   1 year          No
310  512 GB  0 GB  Mac  64-bit            0 GB  Casual   1 year          No

    msoffice   Price   rating  Number of Ratings  Number of Reviews
309       No  159990  4 stars                 32                  5
310       No  172090  4 stars                108                 13

In [156]:

apple_task = apple[
    (apple['processor_brand'] == 'Intel') &
    (apple['ram_gb'] == '8 GB') &
    (apple['Price'] < 100000)
]

print(apple_task)

Empty DataFrame
Columns: [brand, processor_brand, processor_name, processor_gnrtn, ram_gb, ram_type, ssd, hdd, os, os_bit, graphic_card_gb, weight, warranty, Touchscreen, msoffice, Price, rating, Number of Ratings, Number of Reviews]
Index: []

In [157]:
df.head(2)

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5

laptop asus 
processor generation 10
ram type ddr3
os window
graphics card 4 gb
under 50000

In [158]:
asus_task = asus[
    (asus['processor_gnrtn'] == '10th') &
    (asus['ram_type'] == 'DDR4') &
    (asus['os'] == 'Windows') &
    (asus['graphic_card_gb'] == '4 GB') &
    (asus['Price'] < 100000)
]

print(asus_task)

    brand processor_brand processor_name processor_gnrtn ram_gb ram_type  \
219  ASUS           Intel        Core i5            10th   8 GB     DDR4
235  ASUS           Intel        Core i5            10th   8 GB     DDR4
261  ASUS           Intel        Core i5            10th   8 GB     DDR4
320  ASUS           Intel        Core i5            10th   8 GB     DDR4
402  ASUS           Intel        Core i5            10th   8 GB     DDR4
406  ASUS           Intel        Core i5            10th   8 GB     DDR4
409  ASUS           Intel        Core i5            10th   8 GB     DDR4
443  ASUS           Intel        Core i5            10th   8 GB     DDR4
486  ASUS           Intel        Core i7            10th   8 GB     DDR4
580  ASUS           Intel        Core i7            10th  16 GB     DDR4

         ssd      hdd       os  os_bit graphic_card_gb  weight     warranty  \
219   512 GB     0 GB  Windows  64-bit            4 GB  Gaming       1 year
235   512 GB     0 GB  Windows  64-bit            4 GB  Gaming       1 year
261   512 GB     0 GB  Windows  64-bit            4 GB  Gaming       1 year
320   512 GB     0 GB  Windows  64-bit            4 GB  Gaming       1 year
402   512 GB     0 GB  Windows  64-bit            4 GB  Casual  No warranty
406  1024 GB     0 GB  Windows  64-bit            4 GB  Casual       1 year
409  1024 GB     0 GB  Windows  64-bit            4 GB  Casual  No warranty
443   256 GB  1024 GB  Windows  64-bit            4 GB  Gaming  No warranty
486   512 GB     0 GB  Windows  64-bit            4 GB  Gaming  No warranty
580   256 GB  1024 GB  Windows  64-bit            4 GB  Gaming  No warranty

    Touchscreen msoffice  Price   rating  Number of Ratings  Number of Reviews
219          No       No  57990  4 stars               3712                412
235          No      Yes  65990  4 stars               3850                378
261          No       No  63990  3 stars                  0                  0
320          No       No  64990  4 stars                  4                  0
402          No       No  75990  4 stars               1365                137
406          No       No  77990  4 stars                187                 26
409          No       No  82990  4 stars                844                118
443          No       No  55990  4 stars                 23                  0
486          No       No  61990  4 stars                 11                  2
580          No       No  66990  4 stars                 25                  4

In [159]:
asus['Price'].value_counts()

Price
84990     7
99990     7
35990     6
58990     5
114990    5
         ..
74990     1
73490     1
89990     1
49800     1
149990    1
Name: count, Length: 152, dtype: int64

brand acer
processor name intel
ram 8 gb 
ssd <512
os windows
graphics card 4 gb 
laptop touch
price <700000

In [160]:
acer=df[df["brand"]=="acer"]

In [161]:
acer.head(2)

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
9,acer,AMD,Ryzen 5,10th,4 GB,DDR4,0 GB,512 GB,Windows,32-bit,4 GB,Casual,No warranty,No,No,59990,4 stars,1946,240
10,acer,AMD,Ryzen 5,10th,4 GB,DDR4,0 GB,512 GB,Windows,32-bit,6 GB,Casual,No warranty,No,No,93700,4 stars,259,47

In [162]:
# acer_filter = acer[
#     (acer["processor_brand"] == "Intel")
#     & (acer["ram_gb"] == "8 GB")
#     & (acer["ssd"] == "512 GB")
#     & (acer["os"] == "Windows")
#     & (acer["graphic_card_gb"] == "4 GB")

#     & (acer["Price"] < 100000)
# ]

In [163]:
acer_filter

NameError: name 'acer_filter' is not defined

In [ ]:
df.describe()

               Price  Number of Ratings  Number of Reviews
count     823.000000         823.000000         823.000000
mean    76745.177400         315.301337          37.609964
std     45101.790525        1047.382654         121.728017
min     16990.000000           0.000000           0.000000
25%     46095.000000           0.000000           0.000000
50%     64990.000000          17.000000           2.000000
75%     89636.000000         139.500000          18.000000
max    441990.000000       15279.000000        1947.000000

In [ ]:
df.isnull().sum() # it tell us the null values in the data set

brand                0
processor_brand      0
processor_name       0
processor_gnrtn      0
ram_gb               0
ram_type             0
ssd                  0
hdd                  0
os                   0
os_bit               0
graphic_card_gb      0
weight               0
warranty             0
Touchscreen          0
msoffice             0
Price                0
rating               0
Number of Ratings    0
Number of Reviews    0
dtype: int64

In [ ]:
df.dropna(inplace=True) # it drop the null values in the data set

In [ ]:
df.isnull().sum() # it tell us the null values in the data set

brand                0
processor_brand      0
processor_name       0
processor_gnrtn      0
ram_gb               0
ram_type             0
ssd                  0
hdd                  0
os                   0
os_bit               0
graphic_card_gb      0
weight               0
warranty             0
Touchscreen          0
msoffice             0
Price                0
rating               0
Number of Ratings    0
Number of Reviews    0
dtype: int64

In [ ]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990,3 stars,0,0
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990,3 stars,0,0
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990,3 stars,0,0
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990,3 stars,0,0
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490,4 stars,18,4

In [ ]:
df['brand'].unique() # it tell us the unique values in the brand column

array(['ASUS', 'Lenovo', 'acer', 'Avita', 'HP', 'DELL', 'MSI', 'APPLE'],
      dtype=object)

In [ ]:
df['processor_brand'].unique() # it tell us the unique values in the processor brand column

array(['Intel', 'AMD', 'M1'], dtype=object)

In [ ]:
df['processor_name'].unique() # it tell us the unique values in the processor name column

array(['Core i3', 'Core i5', 'Celeron Dual', 'Ryzen 5', 'Core i7',
       'Core i9', 'M1', 'Pentium Quad', 'Ryzen 3', 'Ryzen 7', 'Ryzen 9'],
      dtype=object)

In [ ]:
df['processor_gnrtn'].unique() # it tell us the unique values in the processor generation column

array(['10th', 'Not Available', '11th', '7th', '8th', '9th', '4th',
       '12th'], dtype=object)

In [ ]:
df['ram_gb'].unique() # it tell us the unique values in the ram gb column

array(['4 GB', '8 GB', '16 GB', '32 GB'], dtype=object)

In [ ]:
df['ram_type'].unique() # it tell us the unique values in the ram type column

array(['DDR4', 'LPDDR4', 'LPDDR4X', 'DDR5', 'DDR3', 'LPDDR3'],
      dtype=object)

In [ ]:
df['ssd'].unique() # it tell us the unique values in the ssd column

array(['0 GB', '512 GB', '256 GB', '128 GB', '1024 GB', '2048 GB',
       '3072 GB'], dtype=object)

In [ ]:
df['hdd'].unique() # it tell us the unique values in the hdd column

array(['1024 GB', '0 GB', '512 GB', '2048 GB'], dtype=object)

In [ ]:
df['os_bit'].unique() # it tell us the unique values in the os bit column

array(['64-bit', '32-bit'], dtype=object)

In [ ]:
df['graphic_card_gb'].unique() # it tell us the unique values in the graphic card gb column

array(['0 GB', '2 GB', '4 GB', '6 GB', '8 GB'], dtype=object)

In [ ]:
df['Touchscreen'].unique() # it tell us the unique values in the touchscreen column

array(['No', 'Yes'], dtype=object)

In [ ]:
df['msoffice'].unique() # it tell us the unique values in the ms office column

array(['No', 'Yes'], dtype=object)

In [177]:
import sklearn

In [178]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [179]:
encoder=LabelEncoder()

In [180]:
output=encoder.fit_transform(df['brand'])

In [181]:
output.__class__

numpy.ndarray

In [182]:
output

array([1, 5, 5, 1, 1, 1, 1, 1, 5, 7, 7, 7, 2, 1, 1, 4, 4, 5, 4, 5, 1, 1,
       4, 4, 1, 5, 1, 1, 4, 3, 4, 7, 1, 1, 5, 5, 3, 1, 5, 3, 3, 5, 1, 5,
       3, 1, 5, 3, 3, 3, 3, 5, 1, 5, 5, 5, 5, 4, 6, 3, 1, 5, 5, 3, 7, 3,
       1, 5, 1, 5, 1, 5, 4, 5, 1, 4, 3, 3, 5, 3, 5, 1, 3, 1, 1, 4, 1, 4,
       4, 1, 1, 1, 1, 1, 5, 3, 4, 4, 1, 6, 4, 6, 1, 5, 1, 4, 4, 1, 3, 4,
       3, 3, 1, 5, 4, 4, 4, 1, 4, 1, 1, 1, 1, 4, 4, 1, 3, 5, 3, 4, 1, 5,
       3, 3, 3, 4, 1, 3, 5, 1, 1, 3, 3, 5, 4, 4, 3, 4, 1, 4, 1, 1, 3, 1,
       4, 3, 1, 3, 4, 5, 1, 7, 3, 1, 3, 1, 1, 1, 3, 1, 1, 3, 3, 3, 1, 3,
       7, 3, 3, 3, 1, 3, 3, 3, 3, 3, 3, 3, 1, 1, 4, 4, 5, 5, 5, 5, 7, 7,
       7, 1, 3, 3, 4, 4, 5, 4, 5, 7, 1, 3, 7, 4, 7, 1, 5, 4, 4, 5, 4, 1,
       5, 5, 5, 5, 1, 5, 7, 5, 1, 1, 5, 1, 6, 1, 6, 1, 3, 3, 5, 1, 4, 1,
       4, 4, 7, 3, 1, 1, 3, 3, 1, 6, 4, 1, 5, 5, 4, 7, 1, 4, 3, 1, 4, 1,
       5, 1, 4, 3, 3, 1, 5, 5, 3, 5, 1, 5, 3, 6, 1, 5, 3, 5, 5, 1, 4, 5,
       5, 4, 3, 5, 5, 1, 6, 3, 5, 1, 3, 3, 3, 1, 3, 6, 1, 6, 3, 1, 3, 3,
       3, 0, 0, 6, 6, 5, 5, 4, 4, 5, 5, 7, 1, 6, 4, 5, 5, 7, 4, 1, 7, 1,
       4, 5, 3, 4, 3, 3, 5, 1, 4, 1, 5, 3, 5, 1, 6, 1, 5, 3, 4, 1, 5, 1,
       1, 5, 3, 3, 5, 3, 3, 1, 3, 4, 1, 4, 3, 7, 5, 3, 1, 4, 6, 3, 3, 3,
       3, 1, 4, 3, 6, 1, 1, 1, 1, 5, 5, 3, 1, 5, 2, 3, 3, 2, 1, 2, 2, 1,
       5, 4, 2, 2, 4, 5, 1, 5, 1, 1, 1, 0, 0, 1, 1, 1, 3, 5, 5, 5, 7, 7,
       3, 7, 1, 6, 5, 5, 5, 7, 3, 1, 7, 1, 1, 3, 1, 6, 6, 6, 4, 4, 4, 7,
       4, 7, 1, 1, 7, 1, 3, 7, 7, 3, 1, 5, 1, 1, 5, 3, 1, 1, 3, 4, 3, 5,
       1, 3, 5, 1, 1, 3, 3, 3, 3, 3, 5, 1, 3, 7, 3, 6, 3, 2, 2, 2, 2, 2,
       2, 1, 1, 6, 5, 5, 5, 1, 5, 4, 1, 5, 6, 4, 3, 1, 4, 6, 4, 5, 6, 6,
       6, 4, 1, 3, 1, 6, 4, 4, 3, 6, 5, 5, 3, 4, 6, 1, 1, 5, 1, 5, 5, 4,
       5, 5, 3, 1, 6, 6, 1, 1, 1, 4, 1, 6, 1, 1, 3, 4, 6, 5, 1, 6, 4, 4,
       5, 6, 4, 6, 7, 4, 3, 1, 4, 5, 1, 1, 1, 5, 1, 1, 1, 5, 1, 4, 2, 5,
       4, 4, 5, 7, 1, 1, 4, 6, 1, 1, 7, 6, 1, 7, 7, 7, 7, 6, 1, 1, 1, 5,
       1, 6, 6, 6, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 4, 1, 7, 3, 1, 3, 1, 1, 1, 1, 4, 1,
       3, 3, 3, 1, 3, 1, 1, 7, 4, 4, 7, 4, 3, 3, 3, 4, 3, 3, 3, 3, 4, 5,
       3, 4, 3, 3, 3, 3, 6, 3, 4, 5, 5, 4, 6, 4, 7, 5, 7, 5, 6, 3, 4, 5,
       4, 3, 4, 4, 1, 1, 4, 1, 4, 4, 4, 4, 1, 3, 3, 4, 3, 3, 5, 1, 4, 5,
       4, 1, 4, 7, 4, 5, 3, 6, 7, 4, 7, 4, 1, 7, 1, 5, 4, 3, 4, 1, 4, 4,
       3, 5, 4, 3, 1, 5, 1, 1, 5, 4, 3, 1, 4, 1, 1, 1, 1, 1, 5, 1, 3, 1,
       1, 1, 5, 1, 6, 5, 5, 4, 1, 5, 4, 1, 5, 7, 1, 4, 3, 5, 5, 5, 1, 3,
       4, 5, 4, 4, 6, 1, 4, 4, 1, 1, 7, 1, 4, 1, 5, 1, 1, 5, 1, 1, 1, 1,
       4, 7, 7, 5, 1, 1, 1, 1, 1, 1, 6, 1, 1, 1, 1, 4, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 5])

In [183]:
output.shape

(823,)

In [184]:
df['brand']=output

In [185]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,1,Intel,Core i3,0,2,1,0,1,Windows,1,0,Casual,No warranty,0,0,34649,2 stars,3,0
1,5,Intel,Core i3,0,2,1,0,1,Windows,1,0,Casual,No warranty,0,0,38999,3 stars,65,5
2,5,Intel,Core i3,0,2,1,0,1,Windows,1,0,Casual,No warranty,0,0,39999,3 stars,8,1
3,1,Intel,Core i5,0,3,1,6,0,Windows,0,1,Casual,No warranty,0,0,69990,3 stars,0,0
4,1,Intel,Celeron Dual,7,2,1,0,3,Windows,1,0,Casual,No warranty,0,0,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,1,AMD,Ryzen 9,7,2,1,1,0,Windows,1,0,Casual,1 year,0,0,135990,3 stars,0,0
819,1,AMD,Ryzen 9,7,2,1,1,0,Windows,1,0,Casual,1 year,0,0,144990,3 stars,0,0
820,1,AMD,Ryzen 9,7,2,1,1,0,Windows,1,2,Casual,1 year,0,0,149990,3 stars,0,0
821,1,AMD,Ryzen 9,7,2,1,1,0,Windows,1,2,Casual,1 year,0,0,142990,3 stars,0,0
822,5,AMD,Ryzen 5,0,3,1,6,0,DOS,1,0,ThinNlight,No warranty,0,0,57490,4 stars,18,4

In [186]:
output=encoder.fit_transform(df['processor_brand'])

In [187]:
output.__class__

numpy.ndarray

In [188]:
output

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0])

In [189]:
output.shape

(823,)

In [190]:
df['processor_brand']=output

In [191]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,1,1,Core i3,0,2,1,0,1,Windows,1,0,Casual,No warranty,0,0,34649,2 stars,3,0
1,5,1,Core i3,0,2,1,0,1,Windows,1,0,Casual,No warranty,0,0,38999,3 stars,65,5
2,5,1,Core i3,0,2,1,0,1,Windows,1,0,Casual,No warranty,0,0,39999,3 stars,8,1
3,1,1,Core i5,0,3,1,6,0,Windows,0,1,Casual,No warranty,0,0,69990,3 stars,0,0
4,1,1,Celeron Dual,7,2,1,0,3,Windows,1,0,Casual,No warranty,0,0,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,1,0,Ryzen 9,7,2,1,1,0,Windows,1,0,Casual,1 year,0,0,135990,3 stars,0,0
819,1,0,Ryzen 9,7,2,1,1,0,Windows,1,0,Casual,1 year,0,0,144990,3 stars,0,0
820,1,0,Ryzen 9,7,2,1,1,0,Windows,1,2,Casual,1 year,0,0,149990,3 stars,0,0
821,1,0,Ryzen 9,7,2,1,1,0,Windows,1,2,Casual,1 year,0,0,142990,3 stars,0,0
822,5,0,Ryzen 5,0,3,1,6,0,DOS,1,0,ThinNlight,No warranty,0,0,57490,4 stars,18,4

In [192]:
output=encoder.fit_transform(df['processor_name'])

output.__class__



output



output.shape



df['processor_name']=output


df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,1,1,1,0,2,1,0,1,Windows,1,0,Casual,No warranty,0,0,34649,2 stars,3,0
1,5,1,1,0,2,1,0,1,Windows,1,0,Casual,No warranty,0,0,38999,3 stars,65,5
2,5,1,1,0,2,1,0,1,Windows,1,0,Casual,No warranty,0,0,39999,3 stars,8,1
3,1,1,2,0,3,1,6,0,Windows,0,1,Casual,No warranty,0,0,69990,3 stars,0,0
4,1,1,0,7,2,1,0,3,Windows,1,0,Casual,No warranty,0,0,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,1,0,10,7,2,1,1,0,Windows,1,0,Casual,1 year,0,0,135990,3 stars,0,0
819,1,0,10,7,2,1,1,0,Windows,1,0,Casual,1 year,0,0,144990,3 stars,0,0
820,1,0,10,7,2,1,1,0,Windows,1,2,Casual,1 year,0,0,149990,3 stars,0,0
821,1,0,10,7,2,1,1,0,Windows,1,2,Casual,1 year,0,0,142990,3 stars,0,0
822,5,0,8,0,3,1,6,0,DOS,1,0,ThinNlight,No warranty,0,0,57490,4 stars,18,4

In [193]:
output=encoder.fit_transform(df['processor_gnrtn'])

output.__class__



output



output.shape



df['processor_gnrtn']=output


df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,1,1,1,0,2,1,0,1,Windows,1,0,Casual,No warranty,0,0,34649,2 stars,3,0
1,5,1,1,0,2,1,0,1,Windows,1,0,Casual,No warranty,0,0,38999,3 stars,65,5
2,5,1,1,0,2,1,0,1,Windows,1,0,Casual,No warranty,0,0,39999,3 stars,8,1
3,1,1,2,0,3,1,6,0,Windows,0,1,Casual,No warranty,0,0,69990,3 stars,0,0
4,1,1,0,7,2,1,0,3,Windows,1,0,Casual,No warranty,0,0,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,1,0,10,7,2,1,1,0,Windows,1,0,Casual,1 year,0,0,135990,3 stars,0,0
819,1,0,10,7,2,1,1,0,Windows,1,0,Casual,1 year,0,0,144990,3 stars,0,0
820,1,0,10,7,2,1,1,0,Windows,1,2,Casual,1 year,0,0,149990,3 stars,0,0
821,1,0,10,7,2,1,1,0,Windows,1,2,Casual,1 year,0,0,142990,3 stars,0,0
822,5,0,8,0,3,1,6,0,DOS,1,0,ThinNlight,No warranty,0,0,57490,4 stars,18,4

In [194]:
output=encoder.fit_transform(df['ram_gb'])

output.__class__



output



output.shape



df['ram_gb']=output


df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,1,1,1,0,2,1,0,1,Windows,1,0,Casual,No warranty,0,0,34649,2 stars,3,0
1,5,1,1,0,2,1,0,1,Windows,1,0,Casual,No warranty,0,0,38999,3 stars,65,5
2,5,1,1,0,2,1,0,1,Windows,1,0,Casual,No warranty,0,0,39999,3 stars,8,1
3,1,1,2,0,3,1,6,0,Windows,0,1,Casual,No warranty,0,0,69990,3 stars,0,0
4,1,1,0,7,2,1,0,3,Windows,1,0,Casual,No warranty,0,0,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,1,0,10,7,2,1,1,0,Windows,1,0,Casual,1 year,0,0,135990,3 stars,0,0
819,1,0,10,7,2,1,1,0,Windows,1,0,Casual,1 year,0,0,144990,3 stars,0,0
820,1,0,10,7,2,1,1,0,Windows,1,2,Casual,1 year,0,0,149990,3 stars,0,0
821,1,0,10,7,2,1,1,0,Windows,1,2,Casual,1 year,0,0,142990,3 stars,0,0
822,5,0,8,0,3,1,6,0,DOS,1,0,ThinNlight,No warranty,0,0,57490,4 stars,18,4

In [195]:
output=encoder.fit_transform(df['ram_type'])

output.__class__



output



output.shape



df['ram_type']=output


df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,1,1,1,0,2,1,0,1,Windows,1,0,Casual,No warranty,0,0,34649,2 stars,3,0
1,5,1,1,0,2,1,0,1,Windows,1,0,Casual,No warranty,0,0,38999,3 stars,65,5
2,5,1,1,0,2,1,0,1,Windows,1,0,Casual,No warranty,0,0,39999,3 stars,8,1
3,1,1,2,0,3,1,6,0,Windows,0,1,Casual,No warranty,0,0,69990,3 stars,0,0
4,1,1,0,7,2,1,0,3,Windows,1,0,Casual,No warranty,0,0,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,1,0,10,7,2,1,1,0,Windows,1,0,Casual,1 year,0,0,135990,3 stars,0,0
819,1,0,10,7,2,1,1,0,Windows,1,0,Casual,1 year,0,0,144990,3 stars,0,0
820,1,0,10,7,2,1,1,0,Windows,1,2,Casual,1 year,0,0,149990,3 stars,0,0
821,1,0,10,7,2,1,1,0,Windows,1,2,Casual,1 year,0,0,142990,3 stars,0,0
822,5,0,8,0,3,1,6,0,DOS,1,0,ThinNlight,No warranty,0,0,57490,4 stars,18,4

In [196]:
output=encoder.fit_transform(df['ssd'])

output.__class__



output



output.shape



df['ssd']=output


df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,1,1,1,0,2,1,0,1,Windows,1,0,Casual,No warranty,0,0,34649,2 stars,3,0
1,5,1,1,0,2,1,0,1,Windows,1,0,Casual,No warranty,0,0,38999,3 stars,65,5
2,5,1,1,0,2,1,0,1,Windows,1,0,Casual,No warranty,0,0,39999,3 stars,8,1
3,1,1,2,0,3,1,6,0,Windows,0,1,Casual,No warranty,0,0,69990,3 stars,0,0
4,1,1,0,7,2,1,0,3,Windows,1,0,Casual,No warranty,0,0,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,1,0,10,7,2,1,1,0,Windows,1,0,Casual,1 year,0,0,135990,3 stars,0,0
819,1,0,10,7,2,1,1,0,Windows,1,0,Casual,1 year,0,0,144990,3 stars,0,0
820,1,0,10,7,2,1,1,0,Windows,1,2,Casual,1 year,0,0,149990,3 stars,0,0
821,1,0,10,7,2,1,1,0,Windows,1,2,Casual,1 year,0,0,142990,3 stars,0,0
822,5,0,8,0,3,1,6,0,DOS,1,0,ThinNlight,No warranty,0,0,57490,4 stars,18,4

In [197]:
output=encoder.fit_transform(df['hdd'])

output.__class__



output



output.shape



df['hdd']=output


df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,1,1,1,0,2,1,0,1,Windows,1,0,Casual,No warranty,0,0,34649,2 stars,3,0
1,5,1,1,0,2,1,0,1,Windows,1,0,Casual,No warranty,0,0,38999,3 stars,65,5
2,5,1,1,0,2,1,0,1,Windows,1,0,Casual,No warranty,0,0,39999,3 stars,8,1
3,1,1,2,0,3,1,6,0,Windows,0,1,Casual,No warranty,0,0,69990,3 stars,0,0
4,1,1,0,7,2,1,0,3,Windows,1,0,Casual,No warranty,0,0,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,1,0,10,7,2,1,1,0,Windows,1,0,Casual,1 year,0,0,135990,3 stars,0,0
819,1,0,10,7,2,1,1,0,Windows,1,0,Casual,1 year,0,0,144990,3 stars,0,0
820,1,0,10,7,2,1,1,0,Windows,1,2,Casual,1 year,0,0,149990,3 stars,0,0
821,1,0,10,7,2,1,1,0,Windows,1,2,Casual,1 year,0,0,142990,3 stars,0,0
822,5,0,8,0,3,1,6,0,DOS,1,0,ThinNlight,No warranty,0,0,57490,4 stars,18,4

In [198]:

output=encoder.fit_transform(df['os_bit'])

output.__class__



output



output.shape



df['os_bit']=output


df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,1,1,1,0,2,1,0,1,Windows,1,0,Casual,No warranty,0,0,34649,2 stars,3,0
1,5,1,1,0,2,1,0,1,Windows,1,0,Casual,No warranty,0,0,38999,3 stars,65,5
2,5,1,1,0,2,1,0,1,Windows,1,0,Casual,No warranty,0,0,39999,3 stars,8,1
3,1,1,2,0,3,1,6,0,Windows,0,1,Casual,No warranty,0,0,69990,3 stars,0,0
4,1,1,0,7,2,1,0,3,Windows,1,0,Casual,No warranty,0,0,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,1,0,10,7,2,1,1,0,Windows,1,0,Casual,1 year,0,0,135990,3 stars,0,0
819,1,0,10,7,2,1,1,0,Windows,1,0,Casual,1 year,0,0,144990,3 stars,0,0
820,1,0,10,7,2,1,1,0,Windows,1,2,Casual,1 year,0,0,149990,3 stars,0,0
821,1,0,10,7,2,1,1,0,Windows,1,2,Casual,1 year,0,0,142990,3 stars,0,0
822,5,0,8,0,3,1,6,0,DOS,1,0,ThinNlight,No warranty,0,0,57490,4 stars,18,4

In [199]:



output=encoder.fit_transform(df['graphic_card_gb'])

output.__class__



output



output.shape



df['graphic_card_gb']=output


df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,1,1,1,0,2,1,0,1,Windows,1,0,Casual,No warranty,0,0,34649,2 stars,3,0
1,5,1,1,0,2,1,0,1,Windows,1,0,Casual,No warranty,0,0,38999,3 stars,65,5
2,5,1,1,0,2,1,0,1,Windows,1,0,Casual,No warranty,0,0,39999,3 stars,8,1
3,1,1,2,0,3,1,6,0,Windows,0,1,Casual,No warranty,0,0,69990,3 stars,0,0
4,1,1,0,7,2,1,0,3,Windows,1,0,Casual,No warranty,0,0,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,1,0,10,7,2,1,1,0,Windows,1,0,Casual,1 year,0,0,135990,3 stars,0,0
819,1,0,10,7,2,1,1,0,Windows,1,0,Casual,1 year,0,0,144990,3 stars,0,0
820,1,0,10,7,2,1,1,0,Windows,1,2,Casual,1 year,0,0,149990,3 stars,0,0
821,1,0,10,7,2,1,1,0,Windows,1,2,Casual,1 year,0,0,142990,3 stars,0,0
822,5,0,8,0,3,1,6,0,DOS,1,0,ThinNlight,No warranty,0,0,57490,4 stars,18,4

In [200]:




output=encoder.fit_transform(df['Touchscreen'])

output.__class__



output



output.shape



df['Touchscreen']=output


df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,1,1,1,0,2,1,0,1,Windows,1,0,Casual,No warranty,0,0,34649,2 stars,3,0
1,5,1,1,0,2,1,0,1,Windows,1,0,Casual,No warranty,0,0,38999,3 stars,65,5
2,5,1,1,0,2,1,0,1,Windows,1,0,Casual,No warranty,0,0,39999,3 stars,8,1
3,1,1,2,0,3,1,6,0,Windows,0,1,Casual,No warranty,0,0,69990,3 stars,0,0
4,1,1,0,7,2,1,0,3,Windows,1,0,Casual,No warranty,0,0,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,1,0,10,7,2,1,1,0,Windows,1,0,Casual,1 year,0,0,135990,3 stars,0,0
819,1,0,10,7,2,1,1,0,Windows,1,0,Casual,1 year,0,0,144990,3 stars,0,0
820,1,0,10,7,2,1,1,0,Windows,1,2,Casual,1 year,0,0,149990,3 stars,0,0
821,1,0,10,7,2,1,1,0,Windows,1,2,Casual,1 year,0,0,142990,3 stars,0,0
822,5,0,8,0,3,1,6,0,DOS,1,0,ThinNlight,No warranty,0,0,57490,4 stars,18,4

In [201]:





output=encoder.fit_transform(df['msoffice'])

output.__class__



output



output.shape



df['msoffice']=output


df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,1,1,1,0,2,1,0,1,Windows,1,0,Casual,No warranty,0,0,34649,2 stars,3,0
1,5,1,1,0,2,1,0,1,Windows,1,0,Casual,No warranty,0,0,38999,3 stars,65,5
2,5,1,1,0,2,1,0,1,Windows,1,0,Casual,No warranty,0,0,39999,3 stars,8,1
3,1,1,2,0,3,1,6,0,Windows,0,1,Casual,No warranty,0,0,69990,3 stars,0,0
4,1,1,0,7,2,1,0,3,Windows,1,0,Casual,No warranty,0,0,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,1,0,10,7,2,1,1,0,Windows,1,0,Casual,1 year,0,0,135990,3 stars,0,0
819,1,0,10,7,2,1,1,0,Windows,1,0,Casual,1 year,0,0,144990,3 stars,0,0
820,1,0,10,7,2,1,1,0,Windows,1,2,Casual,1 year,0,0,149990,3 stars,0,0
821,1,0,10,7,2,1,1,0,Windows,1,2,Casual,1 year,0,0,142990,3 stars,0,0
822,5,0,8,0,3,1,6,0,DOS,1,0,ThinNlight,No warranty,0,0,57490,4 stars,18,4

In [202]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,1,1,1,0,2,1,0,1,Windows,1,0,Casual,No warranty,0,0,34649,2 stars,3,0
1,5,1,1,0,2,1,0,1,Windows,1,0,Casual,No warranty,0,0,38999,3 stars,65,5
2,5,1,1,0,2,1,0,1,Windows,1,0,Casual,No warranty,0,0,39999,3 stars,8,1
3,1,1,2,0,3,1,6,0,Windows,0,1,Casual,No warranty,0,0,69990,3 stars,0,0
4,1,1,0,7,2,1,0,3,Windows,1,0,Casual,No warranty,0,0,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,1,0,10,7,2,1,1,0,Windows,1,0,Casual,1 year,0,0,135990,3 stars,0,0
819,1,0,10,7,2,1,1,0,Windows,1,0,Casual,1 year,0,0,144990,3 stars,0,0
820,1,0,10,7,2,1,1,0,Windows,1,2,Casual,1 year,0,0,149990,3 stars,0,0
821,1,0,10,7,2,1,1,0,Windows,1,2,Casual,1 year,0,0,142990,3 stars,0,0
822,5,0,8,0,3,1,6,0,DOS,1,0,ThinNlight,No warranty,0,0,57490,4 stars,18,4